// Generated by gencpp from file tutorials/multiplierResponse.msg
// DO NOT EDIT!


#ifndef TUTORIALS_MESSAGE_MULTIPLIERRESPONSE_H
#define TUTORIALS_MESSAGE_MULTIPLIERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorials
{
template <class ContainerAllocator>
struct multiplierResponse_
{
  typedef multiplierResponse_<ContainerAllocator> Type;

  multiplierResponse_()
    : result(0.0)  {
    }
  multiplierResponse_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef float _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::tutorials::multiplierResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorials::multiplierResponse_<ContainerAllocator> const> ConstPtr;

}; // struct multiplierResponse_

typedef ::tutorials::multiplierResponse_<std::allocator<void> > multiplierResponse;

typedef boost::shared_ptr< ::tutorials::multiplierResponse > multiplierResponsePtr;
typedef boost::shared_ptr< ::tutorials::multiplierResponse const> multiplierResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorials::multiplierResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorials::multiplierResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorials::multiplierResponse_<ContainerAllocator1> & lhs, const ::tutorials::multiplierResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorials::multiplierResponse_<ContainerAllocator1> & lhs, const ::tutorials::multiplierResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorials::multiplierResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorials::multiplierResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorials::multiplierResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorials::multiplierResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorials::multiplierResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorials::multiplierResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorials::multiplierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db954e5de3aba73b237d07575e5cac28";
  }

  static const char* value(const ::tutorials::multiplierResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb954e5de3aba73bULL;
  static const uint64_t static_value2 = 0x237d07575e5cac28ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorials::multiplierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorials/multiplierResponse";
  }

  static const char* value(const ::tutorials::multiplierResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorials::multiplierResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 result\n"
;
  }

  static const char* value(const ::tutorials::multiplierResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorials::multiplierResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multiplierResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorials::multiplierResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorials::multiplierResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<float>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIALS_MESSAGE_MULTIPLIERRESPONSE_H
