// Generated by gencpp from file tutorials/multiplier.msg
// DO NOT EDIT!


#ifndef TUTORIALS_MESSAGE_MULTIPLIER_H
#define TUTORIALS_MESSAGE_MULTIPLIER_H

#include <ros/service_traits.h>


#include <tutorials/multiplierRequest.h>
#include <tutorials/multiplierResponse.h>


namespace tutorials
{

struct multiplier
{

typedef multiplierRequest Request;
typedef multiplierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multiplier
} // namespace tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorials::multiplier > {
  static const char* value()
  {
    return "75900da305351b83210613bd5136a6e2";
  }

  static const char* value(const ::tutorials::multiplier&) { return value(); }
};

template<>
struct DataType< ::tutorials::multiplier > {
  static const char* value()
  {
    return "tutorials/multiplier";
  }

  static const char* value(const ::tutorials::multiplier&) { return value(); }
};


// service_traits::MD5Sum< ::tutorials::multiplierRequest> should match
// service_traits::MD5Sum< ::tutorials::multiplier >
template<>
struct MD5Sum< ::tutorials::multiplierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorials::multiplier >::value();
  }
  static const char* value(const ::tutorials::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorials::multiplierRequest> should match
// service_traits::DataType< ::tutorials::multiplier >
template<>
struct DataType< ::tutorials::multiplierRequest>
{
  static const char* value()
  {
    return DataType< ::tutorials::multiplier >::value();
  }
  static const char* value(const ::tutorials::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorials::multiplierResponse> should match
// service_traits::MD5Sum< ::tutorials::multiplier >
template<>
struct MD5Sum< ::tutorials::multiplierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorials::multiplier >::value();
  }
  static const char* value(const ::tutorials::multiplierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorials::multiplierResponse> should match
// service_traits::DataType< ::tutorials::multiplier >
template<>
struct DataType< ::tutorials::multiplierResponse>
{
  static const char* value()
  {
    return DataType< ::tutorials::multiplier >::value();
  }
  static const char* value(const ::tutorials::multiplierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIALS_MESSAGE_MULTIPLIER_H
